### ISSUE TITLE
Every object created and hosted by CRESON is persistent

### ISSUE THREAD

**Issue by diegolovison** [crucial-project/infinispan-creson#3]
When reading the paper I found the following statement: "Every object created and hosted by CRESON is persistent." but looking into the source code we have https://github.com/otrack/infinispan-creson/blob/master/server/src/main/java/org/infinispan/creson/Server.java#L129 it means that Infinispan won't persist that object.

I would like to understand if my assumptions are right.

**Comment by otrack** [comment]
Sorry for the late answer. You are indeed right, when the flag is set, data persistence is disable
